name: Update README
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write to README
        run: |
          repo_name=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          repo_name=$(echo "${repo_name}" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')
          echo "# ${repo_name}" > README.md
          echo '### File structure' >> README.md
          echo '```' >> README.md
          tree -a -I '.*|node_modules' >> README.md
          echo '```' >> README.md
      - name: Push changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Overwrite README with tree structure"
          git push